app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [

    path('', views.inicio, name="inicio"),
    path('dc/', views.dc, name="DC"),
    path('marvel/', views.marvel, name="Marvel"),
    path('mangas/', views.mangas, name="Mangas"),
    path('contacto/', views.contacto, name="contacto"),
    path('carro/', views.carroCompra, name="carro"),
    path('login/', views.login, name="login"),
    path('registro/', views.registro, name="registro"),
    path('logout/', views.salir, name='salir'),
    
]

urlpatterns+=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

carro/urls.py
from django.urls import path
from . import views

app_name = "carro"

urlpatterns = [
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),
    path("compra/", views.finalizar_compra, name="comprar"),
]

comics/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include('app.urls')),
    path('carro/', include('carro.urls')),
    

    path('accounts/', include('django.contrib.auth.urls')),

]

app/models.py
from django.db import models

# Create your models here.

carro/models.py
from django.db import models
from django.contrib.auth.models import User
from servicios.models import Servicio


# Create your models here.

class Compra(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'Compra {self.id} - {self.usuario.username}'

class DetalleCompra(models.Model):
    compra = models.ForeignKey(Compra, related_name='detalles', on_delete=models.CASCADE)
    producto = models.ForeignKey(Servicio, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'Detalle {self.id} - {self.compra.usuario.username} compró {self.cantidad} de {self.producto.titulo}'

servicios/models.py
from django.db import models


# Create your models here.


class Servicio(models.Model):
    CATEGORIAS = [
        ('dc_comics', 'DC Comics'),
        ('marvel_comics', 'MARVEL Comics'),
        ('mangas', 'MANGAS'),
    ]

    titulo = models.CharField(max_length = 50)
    contenido = models.CharField(max_length = 100)
    imagen = models.ImageField(upload_to = 'servicios')
    unidades = models.IntegerField()
    precio = models.DecimalField(max_digits = 10, decimal_places = 2)
    categoria = models.CharField(max_length = 20, choices = CATEGORIAS, default = 'dc_comics')

    class Meta:
        verbose_name = "control de productos"
        verbose_name_plural = "administrador de productos"

    def __str__(self):
        return self.titulo

app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class customUserCreationForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

app/views.py
from django.shortcuts import render, redirect
from servicios.models import Servicio
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, authenticate, login as auth_login
from .forms import customUserCreationForm

# Create your views here.

@login_required
def inicio(request):    
    servicios = Servicio.objects.all()
    return render(request, 'app/inicio.html', {"servicios" : servicios})


def marvel(request):
    servicios = Servicio.objects.filter(categoria = 'marvel_comics')
    return render(request, 'app/marvel.html', {'servicios' : servicios})


def dc(request):
    servicios = Servicio.objects.filter(categoria = 'dc_comics')
    return render(request, 'app/dc.html', {'servicios' : servicios})


def mangas(request):
    servicios = Servicio.objects.filter(categoria = 'mangas')
    return render(request, 'app/mangas.html', {'servicios' : servicios})


def login(request):
    return render(request, 'registration/login.html')


def contacto(request):
    return render(request, 'app/contacto.html')


def registro(request):
    data = {
        'form' : customUserCreationForm()
    }

    if request.method == 'POST':
        user_creation_form = customUserCreationForm(data=request.POST)
        
        if user_creation_form.is_valid():
            user_creation_form.save()

            username = user_creation_form.cleaned_data['username']
            password = user_creation_form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return redirect('inicio')

    return render(request, 'registration/registro.html', data)


def carroCompra(request):
    return render(request, 'app/carroDeCompras.html')


def salir(request):  
    logout(request)
    return redirect('login')

carro/views.py
from django.shortcuts import redirect, get_object_or_404
from django.contrib import messages
from .carro import Carro
from servicios.models import Servicio

def agregar_producto(request, producto_id):
    carro = Carro(request)
    producto = get_object_or_404(Servicio, id=producto_id)
    carro.agregar(producto=producto)
    return redirect(request.META.get('HTTP_REFERER', 'inicio'))

def eliminar_producto(request, producto_id):
    carro = Carro(request)
    producto = get_object_or_404(Servicio, id=producto_id)
    carro.eliminar(producto=producto)
    return redirect(request.META.get('HTTP_REFERER', 'inicio'))

def restar_producto(request, producto_id):
    carro = Carro(request)
    producto = get_object_or_404(Servicio, id=producto_id)
    carro.restar_producto(producto=producto)
    return redirect(request.META.get('HTTP_REFERER', 'inicio'))

def limpiar_carro(request):
    carro = Carro(request)
    carro.limpiar()
    return redirect(request.META.get('HTTP_REFERER', 'inicio'))

def finalizar_compra(request):
    if request.method == 'POST':
        carro = Carro(request)

        compra = carro.comprar(usuario=request.user)

        if compra:
            messages.success(request, "Compra realizada.")
        else:
            messages.error(request, "No hay productos en el carro.")
        return redirect(request.META.get('HTTP_REFERER', 'inicio'))

    return redirect(request.META.get('HTTP_REFERER', 'inicio'))

servicios/views.py
from django.shortcuts import render

# Create your views here.

app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'app/css/styleNavbar.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/styleInicio.css' %}">
    {% block extra_css %}
    
    {% endblock %}
</head>

<body>

    <!--INICIO-NAVBAR-->
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark">
        <div class="container-fluid">
            <a class="navbar-brand me-auto" href="{% url 'inicio' %}">Comics Sharingann</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Comics Sharingann</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <ul class="navbar-nav justify-content-center flex-grow-1 pe-3">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'inicio' %}">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link mx-lg-2" href="{% url 'Marvel' %}">Marvel</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link mx-lg-2" href="{% url 'DC' %}">DC</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link mx-lg-2" href="{% url 'Mangas' %}">Mangas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link mx-lg-2" href="{% url 'contacto' %}">Contacto</a>
                        </li>
                        {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link mx-lg-2" href="{% url 'salir' %}">Salir / Bienvenido {{ user.username | upper }}</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link mx-lg-2" href="{% url 'login' %}">Login</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <!--FIN-NAVBAR-->
    <br>

    <!--INICIO-CAROUSEL-->
    <div class="container-fluid">
        <div id="carouselExample" class="carousel slide">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{% static 'app/img/Img-carusel/img-1.jpg' %}" class="d-block w-100">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'app/img/Img-carusel/img-2.jpg' %}" class="d-block w-100">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'app/img/Img-carusel/img-3.jpg' %}" class="d-block w-100">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'app/img/Img-carusel/img-4.jpg' %}" class="d-block w-100">
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>
    <!--FIN-CAROUSEL-->
    <br>

    <div class="container">
        <div style="float: right;">
            {% include "carro/widget.html" %}
        </div>
    </div>

    <div class="container">
        <div class="row">
    {% block content %}

    {% endblock %}
        </div>
    </div>


    <!--INICIO-FOOTER-->
    <footer class="bg-secondary-emphasis text-center footer">
        <div class="text-center p-3 txt">
            <p>Dirección: Av. Ricardo Cumming 315-413, Santiago Region metropolitana</p>
            <p>Telefono: +56994532442</p>
            © 2024 COMICS SHARINGANN CHILE
        </div>
    </footer>
    <!--FIN-FOOTER-->


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous">
    </script>
</body>

</html>

app/templates/app/contacto.html
<!DOCTYPE html>
<html lang="en">
{% load static %}


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'app/css/styleNavbar.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/styleInicio.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/styleContacto.css' %}">

<body>

    <!--INICIO-NAVBAR-->
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark">
        <div class="container-fluid">
            <a class="navbar-brand me-auto" href="{% url 'inicio' %}">Comics Sharingann</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar"
                aria-controls="offcanvasNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar"
                aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Comics Sharingann</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <ul class="navbar-nav justify-content-center flex-grow-1 pe-3">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'inicio' %}">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link mx-lg-2" href="{% url 'Marvel' %}">Marvel</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link mx-lg-2" href="{% url 'DC' %}">DC</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link mx-lg-2" href="{% url 'Mangas' %}">Mangas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link mx-lg-2" href="{% url 'contacto' %}">Contacto</a>
                        </li>
                        {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link mx-lg-2" href="{% url 'salir' %}">Salir / Bienvenido {{ user.username | upper }}</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link mx-lg-2" href="{% url 'login' %}">Login</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <!--FIN-NAVBAR-->
    <br>

    <!--INICIO-CAROUSEL-->
    <div class="container-fluid">
        <div id="carouselExample" class="carousel slide">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{% static 'app/img/Img-carusel/img-1.jpg' %}" class="d-block w-100">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'app/img/Img-carusel/img-2.jpg' %}" class="d-block w-100">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'app/img/Img-carusel/img-3.jpg' %}" class="d-block w-100">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'app/img/Img-carusel/img-4.jpg' %}" class="d-block w-100">
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>
    <!--FIN-CAROUSEL-->
    <br>

    <!--INICIO-FORMULARIO-DE-CONTACTO-->
    <div class="container">
        <div class="formBox txt">
            <h1>Envianos un mensaje</h1>
            <img src="{% static 'app/img/brandContacto.jpg' %}">
            <form id="formLogin">
                <div class="mb-3">
                    <label for="correo" class="form-label">Direccion de correo:</label>
                    <input type="text" class="form-control" id="correo" required>
                </div>
                <div class="mb-3">
                    <label for="nombre" class="form-label">Nombre:</label>
                    <input type="text" class="form-control" id="nombre" required>
                </div>
                <div class="mb-3">
                    <label for="mensaje" class="form-label">Mensaje:</label>
                    <textarea class="form-control" id="mensaje" placeholder="Dejanos tu mensaje" required></textarea>
                </div>
                <div class="d-flex justify-content-center">
                    <input type="submit" id="btnIngresar" value="Ingresar" class="boton" href="{% url 'inicio' %}">
                </div>
                <br>
                <p id="error" style=" color: white; text-align: center;"></p>
            </form>
        </div>
    </div>
    <!--FIN-FORMULARIO-DE-CONTACTO-->

    <!--INICIO-FOOTER-->
    <footer class="bg-secondary-emphasis text-center footer">
        <div class="text-center p-3 txt">
            <p>Dirección: Av. Ricardo Cumming 315-413, Santiago Region metropolitana</p>
            <p>Telefono: +56994532442</p>
            © 2024 COMICS SHARINGANN CHILE
        </div>
    </footer>
    <!--FIN-FOOTER-->


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous">
    </script>

    <script src="{% static 'app/js/contacto.js' %}"></script>
</body>

</html>

app/templates/app/dc.html
{% extends 'app/base.html' %}
{% load static %}


{% block title %}

DC Comics Sharingann

{% endblock %}


{% block extra_css %}
<link rel="stylesheet" href="{% static 'app/css/styleProductos.css' %}">
{% endblock %}


{% block content %}
<h1 class="text-center">DC COMICS</h1>
<br>

<!--INICIO-CARD-PRODUCTOS-->
{% for servicio in servicios %}
<div class="col-12 col-md-6 col-lg-4 mb-3" data-id="{{ servicio.id }}">
    <div class="card h-100">
        <div class="row g-0">
            <div class="col-4 col-md-12">
                <img src="{{ servicio.imagen.url }}" class="img-fluid rounded-start">
            </div>
            <div class="col-8 col-md-12">
                <div class="card-body">
                    <h5 class="card-title">{{ servicio.titulo }}</h5>
                    <h1 class="text-primary">Precio: <span class="precio">${{ servicio.precio }}</span></h1>
                    <p class="card-text"><small class="text-body-secondary">{{servicio.contenido}}</small></p>
                    <div class="d-flex justify-content-left">
                        <a href="{% url 'carro:agregar' servicio.id %}" class="btn btn-success">Añadir al carro</a>
                        <button class="btn btn-info" onclick="openModal('{{ servicio.id }}')">Ver más</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<!--FIN-CARD-PRODUCTOS-->

<!--INICIO MODAL-->
<div id="productModal" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <h2 id="modalTitulo"></h2>
        <img id="modalImg" class="img-fluid rounded">
        <h1 class="text-primary">Precio: <span id="modalPrecio"></span></h1>
    </div>
</div>
<!--FIN MODAL-->

<script src="{% static 'app/js/modal.js' %}"></script>
{% endblock %}

app/templates/app/inicio.html
{% extends 'app/base.html' %}
{% load static %}


{% block title %}

Inicio Comics Sharingann

{% endblock %}


{% block extra_css %}
<link rel="stylesheet" href="{% static 'app/css/styleProductos.css' %}">
{% endblock %}


{% block content %}
<h1 class="text-center">PRODUCTOS</h1>
<br>

<!--INICIO-CARD-PRODUCTOS-->
{% for servicio in servicios %}
<div class="col-12 col-md-6 col-lg-4 mb-3" data-id="{{ servicio.id }}">
    <div class="card h-100">
        <div class="row g-0">
            <div class="col-4 col-md-12">
                <img src="{{servicio.imagen.url}}" class="img-fluid rounded-start">
            </div>
            <div class="col-8 col-md-12">
                <div class="card-body">
                    <h5 class="card-title">{{servicio.titulo}}</h5>
                    <h1 class="text-primary">Precio: <span class="precio">${{servicio.precio}}</span></h1>
                    <p class="card-text"><small class="text-body-secondary">{{servicio.contenido}}</small></p>
                    <div class="d-flex justify-content-left">
                        <a href="{% url 'carro:agregar' servicio.id %}" class="btn btn-success">Añadir al
                            carro</a>
                        <button class="btn btn-info" onclick="openModal('{{ servicio.id }}')">Ver más</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<!--FIN-CARD-PRODUCTOS-->

<!--INICIO MODAL-->
<div id="productModal" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <h2 id="modalTitulo"></h2>
        <img id="modalImg" class="img-fluid rounded">
        <h1 class="text-primary">Precio: <span id="modalPrecio"></span></h1>
    </div>
</div>
<!--FIN MODAL-->

<script src="{% static 'app/js/modal.js' %}"></script>


{% endblock %}

app/templates/app/mangas.html
{% extends 'app/base.html' %}
{% load static %}


{% block title %}

Mangas Comics Sharingann

{% endblock %}


{% block extra_css %}
<link rel="stylesheet" href="{% static 'app/css/styleProductos.css' %}">
{% endblock %}


{% block content %}
<h1 class="text-center">MANGAS</h1>
<br>

<!--INICIO-CARD-PRODUCTOS-->
{% for servicio in servicios %}
<div class="col-12 col-md-6 col-lg-4 mb-3" data-id="{{ servicio.id }}">
    <div class="card h-100">
        <div class="row g-0">
            <div class="col-4 col-md-12">
                <img src="{{ servicio.imagen.url }}" class="img-fluid rounded-start">
            </div>
            <div class="col-8 col-md-12">
                <div class="card-body">
                    <h5 class="card-title">{{ servicio.titulo }}</h5>
                    <h1 class="text-primary">Precio: <span class="precio">${{ servicio.precio }}</span></h1>
                    <p class="card-text"><small class="text-body-secondary">{{servicio.contenido}}</small></p>
                    <div class="d-flex justify-content-left">
                        <a href="{% url 'carro:agregar' servicio.id %}" class="btn btn-success">Añadir al carro</a>
                        <button class="btn btn-info" onclick="openModal('{{ servicio.id }}')">Ver más</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<!--FIN-CARD-PRODUCTOS-->

<!--INICIO MODAL-->
<div id="productModal" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <h2 id="modalTitulo"></h2>
        <img id="modalImg" class="img-fluid rounded">
        <h1 class="text-primary">Precio: <span id="modalPrecio"></span></h1>
    </div>
</div>
<!--FIN MODAL-->

<script src="{% static 'app/js/modal.js' %}"></script>
{% endblock %}

app/templates/app/marvel.html
{% extends 'app/base.html' %}
{% load static %}

{% block title %}
Marvel Comics Sharingann
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'app/css/styleProductos.css' %}">
{% endblock %}

{% block content %}
<h1 class="text-center">MARVEL COMICS</h1>
<br>

<!--INICIO-CARD-PRODUCTOS-->
{% for servicio in servicios %}
<div class="col-12 col-md-6 col-lg-4 mb-3" data-id="{{ servicio.id }}">
    <div class="card h-100">
        <div class="row g-0">
            <div class="col-4 col-md-12">
                <img src="{{ servicio.imagen.url }}" class="img-fluid rounded-start">
            </div>
            <div class="col-8 col-md-12">
                <div class="card-body">
                    <h5 class="card-title">{{ servicio.titulo }}</h5>
                    <h1 class="text-primary">Precio: <span class="precio">${{ servicio.precio }}</span></h1>
                    <p class="card-text"><small class="text-body-secondary">{{servicio.contenido}}</small></p>
                    <div class="d-flex justify-content-left">
                        <a href="{% url 'carro:agregar' servicio.id %}" class="btn btn-success">Añadir al carro</a>
                        <button class="btn btn-info" onclick="openModal('{{ servicio.id }}')">Ver más</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<!--FIN-CARD-PRODUCTOS-->

<!--INICIO MODAL-->
<div id="productModal" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <h2 id="modalTitulo"></h2>
        <img id="modalImg" class="img-fluid rounded">
        <h1 class="text-primary">Precio: <span id="modalPrecio"></span></h1>
    </div>
</div>
<!--FIN MODAL-->

<script src="{% static 'app/js/modal.js' %}"></script>
{% endblock %}

app/templates/carro/widget.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Carro de Compras</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>


    <!--INICIO-CARRO-DE-COMPRAS-->
    <table class="table table-bordered" style="color: red;">
        <thead>
            <tr>
                <th colspan="3" class="text-center">

                    Carro de compras

                </th>

            </tr>

            <tr>

                <th>Prducto</th>
                <th>Cantidad</th>
                <th>Total</th>

            </tr>


        </thead>

        <tbody>

            {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
            <tr class="text-center">

                <td><img src="{{ value.imagen }}" alt="{{ value.titulo }}" style="max-width: 100px; max-height: 100px;">
                </td>
                <td>{{value.cantidad}}</td>
                <td>

                    <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                    <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a>
                    <br>

                    {{value.precio}} $


                </td>

            </tr>




            {% endfor %}

            {% else %}
            <td colspan="3">
                <div class="alert alert-danger text-center">
                    Carro vacio
                </div>

            </td>



            {% endif %}

        </tbody>


        <tfoot>
            <tr>

                <td colspan="3">
                    Total: {{importe_total_carro}}
                </td>
            <tr>
                <td colspan="3" class="text-center">
                    <form method="post" action="{% url 'carro:comprar' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">Finalizar Compra</button>
                        <br>
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{ message.tags }}">
                                    {{ message }}
                                </div>
                            {% endfor %}
                         {% endif %}
                    </form>
                </td>
            </tr>

            </tr>
        </tfoot>


    </table>
    <!--FIN-CARRO-DE-COMPRAS-->


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous">
        </script>

</body>

</html>